/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBarRouteImport } from './routes/_authenticated/bar'
import { Route as AuthenticatedCardapioRouteImport } from './routes/_authenticated/cardapio'
import { Route as AuthenticatedCozinhaRouteImport } from './routes/_authenticated/cozinha'
import { Route as AuthenticatedMesasRouteImport } from './routes/_authenticated/mesas'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedSalaoRouteImport } from './routes/_authenticated/salao'
import { Route as MTokenRouteImport } from './routes/m.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBarRoute = AuthenticatedBarRouteImport.update({
  id: '/bar',
  path: '/bar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCardapioRoute = AuthenticatedCardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCozinhaRoute = AuthenticatedCozinhaRouteImport.update({
  id: '/cozinha',
  path: '/cozinha',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesasRoute = AuthenticatedMesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalaoRoute = AuthenticatedSalaoRouteImport.update({
  id: '/salao',
  path: '/salao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MTokenRoute = MTokenRouteImport.update({
  id: '/m/$token',
  path: '/m/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bar': typeof AuthenticatedBarRoute
  '/cardapio': typeof AuthenticatedCardapioRoute
  '/cozinha': typeof AuthenticatedCozinhaRoute
  '/mesas': typeof AuthenticatedMesasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/salao': typeof AuthenticatedSalaoRoute
  '/m/$token': typeof MTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bar': typeof AuthenticatedBarRoute
  '/cardapio': typeof AuthenticatedCardapioRoute
  '/cozinha': typeof AuthenticatedCozinhaRoute
  '/mesas': typeof AuthenticatedMesasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/salao': typeof AuthenticatedSalaoRoute
  '/m/$token': typeof MTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/bar': typeof AuthenticatedBarRoute
  '/_authenticated/cardapio': typeof AuthenticatedCardapioRoute
  '/_authenticated/cozinha': typeof AuthenticatedCozinhaRoute
  '/_authenticated/mesas': typeof AuthenticatedMesasRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/salao': typeof AuthenticatedSalaoRoute
  '/m/$token': typeof MTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bar'
    | '/cardapio'
    | '/cozinha'
    | '/mesas'
    | '/painel'
    | '/salao'
    | '/m/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bar'
    | '/cardapio'
    | '/cozinha'
    | '/mesas'
    | '/painel'
    | '/salao'
    | '/m/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/bar'
    | '/_authenticated/cardapio'
    | '/_authenticated/cozinha'
    | '/_authenticated/mesas'
    | '/_authenticated/painel'
    | '/_authenticated/salao'
    | '/m/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MTokenRoute: typeof MTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bar': {
      id: '/_authenticated/bar'
      path: '/bar'
      fullPath: '/bar'
      preLoaderRoute: typeof AuthenticatedBarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cardapio': {
      id: '/_authenticated/cardapio'
      path: '/cardapio'
      fullPath: '/cardapio'
      preLoaderRoute: typeof AuthenticatedCardapioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cozinha': {
      id: '/_authenticated/cozinha'
      path: '/cozinha'
      fullPath: '/cozinha'
      preLoaderRoute: typeof AuthenticatedCozinhaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mesas': {
      id: '/_authenticated/mesas'
      path: '/mesas'
      fullPath: '/mesas'
      preLoaderRoute: typeof AuthenticatedMesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salao': {
      id: '/_authenticated/salao'
      path: '/salao'
      fullPath: '/salao'
      preLoaderRoute: typeof AuthenticatedSalaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/m/$token': {
      id: '/m/$token'
      path: '/m/$token'
      fullPath: '/m/$token'
      preLoaderRoute: typeof MTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBarRoute: typeof AuthenticatedBarRoute
  AuthenticatedCardapioRoute: typeof AuthenticatedCardapioRoute
  AuthenticatedCozinhaRoute: typeof AuthenticatedCozinhaRoute
  AuthenticatedMesasRoute: typeof AuthenticatedMesasRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedSalaoRoute: typeof AuthenticatedSalaoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBarRoute: AuthenticatedBarRoute,
  AuthenticatedCardapioRoute: AuthenticatedCardapioRoute,
  AuthenticatedCozinhaRoute: AuthenticatedCozinhaRoute,
  AuthenticatedMesasRoute: AuthenticatedMesasRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedSalaoRoute: AuthenticatedSalaoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MTokenRoute: MTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
